set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_OSX_DEPLOYMENT_TARGET 9.0)
set(VCPKG_CXX_FLAGS "-fembed-bitcode -mios-version-min=8.0")
set(VCPKG_C_FLAGS "-fembed-bitcode -mios-version-min=8.0")
set(VCPKG_LINKER_FLAGS "-fembed-bitcode -mios-version-min=8.0")
