set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_CXX_FLAGS -fembed-bitcode)
set(VCPKG_C_FLAGS -fembed-bitcode)
set(VCPKG_CXX_FLAGS "-fembed-bitcode -mios-simulator-version-min=9.0")
set(VCPKG_C_FLAGS "-fembed-bitcode -mios-simulator-version-min=9.0")
set(VCPKG_LINKER_FLAGS "-fembed-bitcode -mios-simulator-version-min=9.0")
