# 保存CMAKE_MODULE路径
set(LIBUV_CMAKE_MODULE_PATH_STORY ${CMAKE_MODULE_PATH})
# 设置CMAKE_MODULE路径到当前目录
set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

cmake_policy(SET CMP0012 NEW)
# 查找Findlibuv.cmake
_find_package(${ARGS})
# 恢复之前的CMAKE_MODULE路径
set(CMAKE_MODULE_PATH ${LIBUV_CMAKE_MODULE_PATH_STORY})
